/**
 * Skill Expertise Descriptions
 * Detailed expertise descriptions for each technology
 * Provides comprehensive insight into practical capabilities
 */

export const skillExpertise = {
  // Frontend Technologies
  React: [
    "Component Creation And Structure",
    "JSX Syntax And Rendering",
    "Props And State Management",
    "Hooks (useState, useEffect)",
    "Event Handling And Forms",
    "Component Lifecycle Understanding",
    "Context API For Simple State Sharing",
    "Basic Performance Optimization",
  ],
  "Next.js": [
    "File-Based Routing System",
    "Page Components And Layouts",
    "API Routes Development",
    "Static Site Generation Basics",
    "Image Optimization",
    "Deployment On Vercel",
    "Basic SEO Implementation",
  ],
  TypeScript: [
    "Basic Type Annotations",
    "Interface Definition",
    "Type Safety Implementation",
    "Props Typing In React",
    "Basic Generics Usage",
    "Error Prevention Through Types",
  ],
  JavaScript: [
    "ES6+ Syntax And Features",
    "DOM Manipulation",
    "Event Handling",
    "Async/Await And Promises",
    "Array Methods And Iteration",
    "API Integration With Fetch",
    "Local Storage Management",
  ],
  "Tailwind CSS": [
    "Utility-First CSS Approach",
    "Responsive Design Implementation",
    "Component Styling",
    "Custom Configuration",
    "Dark Mode Implementation",
    "Animation Classes",
  ],
  HTML: [
    "Semantic HTML Structure",
    "Accessibility Best Practices",
    "Forms And Input Validation",
    "Meta Tags And SEO",
    "Responsive Images",
    "Modern HTML5 APIs",
  ],
  CSS: [
    "Flexbox And Grid Layouts",
    "Responsive Design",
    "CSS Animations And Transitions",
    "Custom Properties (Variables)",
    "Media Queries",
    "Cross-Browser Compatibility",
  ],
  Bootstrap: [
    "Grid System",
    "Responsive Components",
    "Utility Classes",
    "Form Components",
    "Navigation Components",
    "Modal And Dropdown Systems",
  ],
  "ShadCN UI": [
    "Component Library Integration",
    "Accessible UI Components",
    "Custom Theming",
    "Form Components",
    "Composable Components",
  ],
  "Next UI": [
    "React Component Library",
    "Modern UI Components",
    "Theme Customization",
    "Responsive Design Patterns",
  ],
  "Framer Motion": [
    "Animation API",
    "Gesture Handling",
    "Layout Animations",
    "Variants System",
    "AnimatePresence For Exit Animations",
  ],
  NextAuth: [
    "Authentication Configuration",
    "OAuth Provider Integration",
    "Session Management",
    "JWT Implementation",
    "Protected Routes",
  ],

  // Backend Technologies
  Java: [
    "Object-Oriented Programming",
    "Basic Syntax And Data Structures",
    "JDBC Database Connectivity",
    "RESTful API Development",
    "Spring Boot Applications",
    "Exception Handling",
    "Unit Testing With JUnit",
  ],
  Python: [
    "Basic Syntax And Data Types",
    "File Handling And I/O",
    "Web Development With Flask/Django",
    "REST API Development",
    "Data Processing With Pandas",
    "Web Scraping With BeautifulSoup",
    "Automation Scripts",
  ],
  "C#": [
    "Object-Oriented Programming Basics",
    "Basic Syntax And Data Types",
    "Database Operations",
    "ASP.NET Core Web APIs",
    "Entity Framework Basics",
    "Unit Testing",
  ],
  "Node.js": [
    "Server-Side JavaScript",
    "Express.js Framework",
    "RESTful API Development",
    "Database Integration",
    "Middleware Implementation",
    "Authentication Systems",
  ],
  MongoDB: [
    "Document Database Operations",
    "CRUD Operations",
    "Schema Design",
    "Aggregation Pipelines",
    "Index Optimization",
    "Database Performance",
  ],
  MySQL: [
    "Relational Database Design",
    "SQL Query Writing",
    "CRUD Operations",
    "Database Schema Management",
    "Joins And Relationships",
    "Query Optimization",
    "Data Integrity And Constraints",
  ],
  PostgreSQL: [
    "Advanced SQL Queries",
    "Database Design",
    "CRUD Operations",
    "Indexing And Performance",
    "JSON Data Types",
    "Transaction Management",
  ],
  Prisma: [
    "ORM Integration",
    "Schema Definition",
    "Type-Safe Database Queries",
    "Migrations Management",
    "Database Relationships",
  ],
  Mongoose: [
    "MongoDB ODM",
    "Schema Modeling",
    "Validation",
    "Middleware Hooks",
    "Population And References",
  ],
  Argon2: [
    "Password Hashing",
    "Security Best Practices",
    "Authentication Systems",
    "Hash Verification",
  ],

  // Cloud & Infrastructure
  "Azure Cloud": [
    "Cloud Service Deployment",
    "Resource Management",
    "DevOps Integration",
    "Service Configuration",
    "Cloud Cost Optimization",
  ],
  AWS: [
    "Cloud Infrastructure Setup",
    "Service Provisioning",
    "Resource Management",
    "Basic Cloud Architecture",
  ],
  "Google Cloud": [
    "Cloud Platform Services",
    "Resource Deployment",
    "Service Configuration",
    "Cloud Integration",
  ],

  // Mobile Development
  "React Native": [
    "Cross-Platform Development",
    "Native Component Integration",
    "Navigation Systems",
    "State Management",
    "API Integration",
    "Mobile-Specific Features",
  ],
  "Expo Go": [
    "Rapid Prototyping",
    "Development Workflow",
    "Device Testing",
    "Build Management",
  ],

  // AI & Machine Learning
  "OpenAI API": [
    "API Integration",
    "GPT Model Implementation",
    "Prompt Design",
    "Response Processing",
    "Chat Completion APIs",
  ],
  "Prompt Engineering": [
    "Effective Prompt Design",
    "Context Optimization",
    "Response Quality Enhancement",
    "System Message Configuration",
  ],
  "Azure AI": [
    "AI Service Integration",
    "Cognitive Services",
    "Model Deployment",
    "AI Pipeline Development",
  ],
  "AI Integration": [
    "AI Feature Implementation",
    "API Integration Patterns",
    "User Experience Enhancement",
    "Performance Optimization",
  ],
  "Machine Learning": [
    "Basic ML Concepts",
    "Data Preprocessing",
    "Model Selection",
    "Training Fundamentals",
  ],

  // Development Tools
  "Visual Studio Code": [
    "Code Editing And Navigation",
    "Extension Management",
    "Debugging Setup",
    "Git Integration",
    "Customization And Shortcuts",
  ],
  Git: [
    "Version Control",
    "Branch Management",
    "Merge Strategies",
    "Conflict Resolution",
    "Collaborative Workflows",
  ],
  BitBucket: [
    "Repository Management",
    "Pull Request Workflows",
    "Code Review Process",
    "Team Collaboration",
  ],
  Docker: [
    "Containerization Basics",
    "Dockerfile Creation",
    "Image Management",
    "Container Deployment",
  ],
  Vercel: [
    "Deployment Automation",
    "Performance Optimization",
    "Domain Management",
    "Environment Configuration",
  ],
  Trello: [
    "Project Organization",
    "Task Management",
    "Team Collaboration",
    "Workflow Setup",
    "Board Customization",
  ],
  npm: [
    "Package Management",
    "Dependency Installation",
    "Script Configuration",
    "Version Management",
    "Registry Publishing",
  ],
  Yarn: [
    "Package Manager",
    "Workspace Management",
    "Dependency Resolution",
    "Lock File Management",
  ],
  Postman: [
    "API Testing",
    "Request Collections",
    "Environment Variables",
    "Automated Testing",
    "API Documentation",
  ],
  "Android Studio": [
    "IDE Navigation And Setup",
    "Project Configuration",
    "Build System Management",
    "Debugging Tools",
    "Emulator Usage",
    "Version Control Integration",
  ],

  // Operating Systems
  Windows: [
    "System Administration",
    "File System Management",
    "Command Line Interface",
    "Software Installation",
    "System Configuration",
    "Troubleshooting And Diagnostics",
    "Network Configuration",
    "Security Best Practices",
    "PowerShell Scripting",
    "Task Automation",
  ],
  Ubuntu: [
    "Linux Distribution Usage",
    "Package Management",
    "Terminal Commands",
    "System Administration",
    "Server Configuration",
  ],
  Linux: [
    "Command Line Proficiency",
    "File System Navigation",
    "Basic System Administration",
    "Shell Scripting",
  ],
  macOS: [
    "macOS Environment",
    "Terminal Usage",
    "Development Tools",
    "System Preferences",
  ],
} as const;
